FROM ubuntu:latest  

# Switch to root user to be able to install packages.  
USER root  

# Install packages.  
RUN apt-get update --fix-missing  
RUN apt-get install -y vim wget unzip 
RUN apt-get install -y nodejs
RUN apt-get install -y npm
RUN apt-get install openjdk-8-jre -y

# Install sonarqube scanner.  
WORKDIR /usr/src  

RUN wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip  

RUN unzip sonar-scanner-cli-4.2.0.1873-linux.zip  
RUN rm sonar-scanner-cli-4.2.0.1873-linux.zip  
RUN mv sonar-scanner-4.2.0.1873-linux /usr/lib/sonar-scanner  

# Create symbolic link.  
RUN ln -s /usr/lib/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner  
ENV SONAR_RUNNER_HOME=/usr/lib/sonar-scanner  
ENV SONAR_USER_HOME=/home/.sonar  

# ADD sonar-entrust.pem /usr/lib/sonar-scanner/jre/lib/security/
# RUN keytool -import -trustcacerts -keystore /usr/lib/sonar-scanner/jre/lib/security/cacerts -storepass changeit -alias sonar-entrust2 -file /usr/lib/sonar-scanner/jre/lib/security/sonar-entrust.pem -noprompt
