apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-test
  template:
    metadata:
      labels:
        name: mongodb-test
    spec:
      containers:
      - image: mongodb
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep 10m; done'
        imagePullPolicy: IfNotPresent
        name: mongodb
        volumeMounts:
          - name: nfs
            mountPath: "/tmp"
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: db
